/*Aggregate Funtions
11. Calculate total revenue.
12. Calculate average order value.
13. Find total quantity sold.
14. Revenue by product category.
15. Revenue by customer.
16. Revenue by country/state.
17. Total orders by customer.
18. Average quantity per order.
19. Highest revenue generated by one order.
20. Lowest revenue generated by one order.
*/

-- Calculate total revenue.
select sum(order_items.quantity * order_items.price) as total_revenue from order_items;

-- Calculate average order value.
select round(avg(order_total),2) as average_order_value
from (
	select order_id, 
		sum(order_items.quantity * order_items.price) as order_total
    from order_items
    group by order_id
) as order_summary;

-- Find total quantity sold.
Select sum(order_items.quantity) as total_quantity_sold from order_items;

-- Revenue by product category.
select p.category,
	sum(oi.quantity * oi.price) as revenue
from order_items oi 
join products p
on oi.product_id = p.product_id
group by p.category
order by revenue;

-- Revenue by customer.
select o.customer_id,
	sum(oi.quantity * oi.price) as revenue
from orders o
join order_items oi 
on o.order_id = oi.order_id
group by o.customer_id
order by revenue desc
limit 10;

-- Revenue by country/state.
select c.country,
	sum(oi.quantity * oi.price) as revenue
from customers c
join orders o
on c.customer_id = o.customer_id
join order_items oi
on o.order_id = oi.order_id
group by c.country
order by revenue desc;

-- Total orders by customer.
select customer_id,
	count(order_id) as total_orders
from orders
group by customer_id
order by total_orders desc;

-- Average quantity per order.
select round(avg(total_quantity),2) as avg_quantity_per_order
from (
	select order_id,
		sum(quantity) as total_quantity
	from order_items
    group by order_id
) as qty_summary;

-- Highest revenue generated by one order.
select order_id,
	sum(quantity * price) as revenue
from order_items
group by order_id
order by revenue desc
limit 1;

-- Lowest revenue generated by one order.
select order_id,
	sum(quantity * price) as revenue
from order_items
group by order_id
order by revenue
limit 1;

